# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eventador
email: hello@eventador.io
description: "Eventador is a high performance real-time data pipeline based on Apache Kafka. Eventador is deployed to Amazon AWS, and delivered as a service."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eventador.io" # the base hostname & protocol for your site
twitter_username: eventadorlabs
github_username:  eventador

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  documentation:
    output: true

exclude: [vendor]
